name: CI/CD for React Frontend with Docker and Nginx

on:
  push:
    branches:
      - main # Runs on push to the main branch
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build React app
        run: npm run build

      - name: Run tests
        run: npm test -- --watchAll=false

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: react-build
          path: build/

  docker:
    name: Build & Push Docker Image
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/react-nginx:latest

  deploy:
    name: Deploy to Server
    needs: docker
    runs-on: ubuntu-latest

    steps:
      - name: SSH into Server & Deploy Container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/react-nginx:latest
            docker stop frontend-app || true
            docker rm frontend-app || true
            docker run -d -p 3000:80 --name frontend-app ${{ secrets.DOCKER_USERNAME }}/react-nginx:latest
